---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  log_level: warning
  require_chef: false
  formula: docker
  state_top:
    base:
      '*':
        - docker

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
      provision_command:
        - apt-get update && apt-get install -y locales ifupdown
        - locale-gen en_US.UTF-8
        - update-locale LANG=en_US.UTF-8
      run_command: /lib/systemd/systemd
  - name: debian-jessie
    driver_config:
      provision_command:
        - apt-get update
      run_command: /lib/systemd/systemd

suites:
  - name: default
  - name: version-1.13.1
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - docker
        docker.sls:
          docker:
            version: '1.13.1*'
    excludes:
      - debian-jessie
      
  - name: version-1.6.2
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - docker
        docker.sls:
          docker:
            version: '1.6.2*'
    excludes:
      - ubuntu-16.04

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
