# vim: sts=2 ts=2 sw=2 et ai

docker:
  process_signature: '/usr/bin/docker'
  install_docker_py: False
  refresh_repo: True
  config: []

  pip:
    pkgname: python-pip
    upgrade: False

  use_upstream_repo: True
  compose_version:

  containers:
    skip_translate: None
    force_present: False
    force_running: False

  kernel:
    pkgs: []
